using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;

namespace Clock.Services;

public sealed class ClockLanguageOption
{
    public ClockLanguageOption(string cultureName, string displayName)
    {
        CultureName = cultureName;
        DisplayName = displayName;
    }

    public string CultureName { get; }
    public string DisplayName { get; }
}

public static class ClockLocalizationService
{
    private static readonly ClockLanguageOption[] LanguageOptions =
    {
        new("en-US", "English (US)"),
        new("en-GB", "English (UK)"),
        new("pt-BR", "Português"),
        new("fr-FR", "Français"),
        new("de-DE", "Deutsch"),
        new("ja-JP", "日本語")
    };

    private static readonly Dictionary<string, Dictionary<string, string>> Translations = new(StringComparer.OrdinalIgnoreCase)
    {
        ["pt"] = new(StringComparer.Ordinal)
        {
            ["Advanced Settings"] = "Configurações avançadas",
            ["Help"] = "Ajuda",
            ["Select language"] = "Selecionar idioma",
            ["Search languages..."] = "Pesquisar idiomas...",
            ["Active Profile"] = "Perfil ativo",
            ["Profile"] = "Perfil",
            ["No user profiles"] = "Nenhum perfil de usuário",
            ["General"] = "Geral",
            ["Alarms"] = "Alarmes",
            ["Profiles"] = "Perfis",
            ["Appearance"] = "Aparência",
            ["Appearance Settings"] = "Configurações de aparência",
            ["Commands"] = "Comandos",
            ["Plugin Config"] = "Configuração do plugin",
            ["Behavior"] = "Comportamento",
            ["Stick clock"] = "Fixar relógio",
            ["Auto Start"] = "Iniciar automaticamente",
            ["Hide during cutscenes"] = "Ocultar durante cutscenes",
            ["Locks or unlocks movement/resizing of the clock window."] = "Bloqueia ou libera mover/redimensionar a janela do relógio.",
            ["Automatically opens the clock after login."] = "Abre o relógio automaticamente após o login.",
            ["Hides only the clock during cutscenes."] = "Oculta apenas o relógio durante cutscenes.",
            ["Command suggestion"] = "Sugestão de comando",
            ["Show a autocompletion list when typing \"/clock\" commands"] = "Mostra uma lista de autocompletar ao digitar comandos \"/clock\"",
            ["Show next on overlay"] = "Mostrar próximo no overlay",
            ["Show on main overlay"] = "Mostrar no overlay principal",
            ["Can't create a Alarm for the past!"] = "Não é possível criar um alarme no passado!",
            ["Repeat"] = "Repetir",
            ["Once"] = "Uma vez",
            ["Daily"] = "Diariamente",
            ["Weekly"] = "Semanalmente",
            ["Weekdays"] = "Dias úteis",
            ["Weekends"] = "Fins de semana",
            ["Clock commands"] = "Comandos do Clock",
            ["No Clock commands found"] = "Nenhum comando do Clock encontrado",
            ["Open Clock settings"] = "Abrir configurações do Clock",
            ["Change the time format"] = "Alterar o formato de hora",
            ["Change the active profile layout"] = "Alterar o layout do perfil ativo",
            ["Compare the current time between two timezones"] = "Comparar a hora atual entre dois fusos",
            ["Lock clock movement"] = "Bloquear movimento do relógio",
            ["Unlock clock movement"] = "Desbloquear movimento do relógio",
            ["Toggle the clock overlay"] = "Alternar o overlay do relógio",
            ["Time Display"] = "Exibição de hora",
            ["Primary Timezone"] = "Fuso horário principal",
            ["Commonly Used"] = "Comumente usado",
            ["Add to favorites"] = "Adicionar aos favoritos",
            ["Remove from favorites"] = "Remover dos favoritos",
            ["Favorite Timezones"] = "Fusos favoritos",
            ["Favorite timezones can be selected to change the current timezone"] = "Fusos favoritos podem ser selecionados para mudar o fuso atual",
            ["No favorite timezones added yet."] = "Nenhum fuso favorito adicionado ainda.",
            ["Didn't find what you are looking for? Try by the country instead:"] = "Não encontrou o que procura? Tente pelo país:",
            ["Select Country"] = "Selecionar país",
            ["Search by country and hit \"✓\" to automaticaly find timezone."] = "Pesquise por país e aperte \"✓\" para encontrar o fuso automaticamente.",
            ["Time Format"] = "Formato de hora",
            ["12-hour"] = "12 horas",
            ["24-hour"] = "24 horas",
            ["12-hour + seconds"] = "12 horas + segundos",
            ["24-hour + seconds"] = "24 horas + segundos",
            ["Weekday + 24-hour"] = "Dia da semana + 24 horas",
            ["Date + 24-hour"] = "Data + 24 horas",
            ["Show Local Time"] = "Mostrar hora local",
            ["Chat Timestamp"] = "Timestamp do chat",
            ["Show custom timestamp"] = "Mostrar timestamp customizado",
            ["Show AM/PM"] = "Mostrar AM/PM",
            ["Custom color"] = "Cor personalizada",
            ["Timestamp timezone"] = "Fuso do timestamp",
            ["Enable \"Add timestamp to messages.\" in char config to work"] = "Ative \"Add timestamp to messages.\" nas configurações do personagem para funcionar",
            ["Recommended to turn off any similar feature"] = "Recomendado desativar qualquer recurso semelhante",
            ["from other plugins to avoid any issues."] = "de outros plugins para evitar problemas.",
            ["Use typed ID: {0}"] = "Usar ID digitado: {0}",
            ["Colon Animation"] = "Animação dos dois pontos",
            ["Default"] = "Padrão",
            ["Always"] = "Sempre",
            ["Hidden"] = "Oculto",
            ["Slow"] = "Lento",
            ["Fast"] = "Rápido",
            ["Create Alarm"] = "Criar alarme",
            ["Alarm Date/Time"] = "Data/hora do alarme",
            ["Alarm Format"] = "Formato do alarme",
            ["You can change it on \"General\""] = "Você pode alterar isso em \"Geral\"",
            ["Sound"] = "Som",
            ["Alarm Message"] = "Mensagem do alarme",
            ["Allow Snooze after trigger"] = "Permitir adiar após disparar",
            ["Snooze Duration"] = "Duração do adiamento",
            ["minutes"] = "minutos",
            ["Add Alarm"] = "Adicionar alarme",
            ["Test Alarm"] = "Testar alarme",
            ["Edit Alarm"] = "Editar alarme",
            ["Alarm notifications are shown in chat and on screen."] = "As notificações de alarme aparecem no chat e na tela.",
            ["Active Alarms"] = "Alarmes ativos",
            ["No alarms created."] = "Nenhum alarme criado.",
            ["No alarms created yet."] = "Nenhum alarme criado ainda.",
            ["Reenable Alarm for today"] = "Reativar alarme para hoje",
            ["Alarm reenabled for today"] = "Alarme reativado para hoje",
            ["Alarm"] = "Alarme",
            ["Alarm updated"] = "Alarme atualizado",
            ["OK"] = "OK",
            ["Ok"] = "Ok",
            ["Test"] = "Teste",
            ["Snooze"] = "Adiamento",
            ["Snooze will trigger at {0}"] = "Adiamento irá disparar às {0}",
            ["Snooze already triggered."] = "Adiamento já disparou.",
            ["Snooze canceled."] = "Adiamento cancelado.",
            ["Alarm snoozed for {0} minutes"] = "Alarme adiado por {0} minutos",
            ["Maintenance Reminders"] = "Lembretes de manutenção",
            ["Enable Maintenance Reminders"] = "Ativar lembretes de manutenção",
            ["Lodestone Language"] = "Idioma do Lodestone",
            ["Check Now"] = "Verificar agora",
            ["Checking..."] = "Verificando...",
            ["Maintenance check is already running."] = "A verificação de manutenção já está em andamento.",
            ["Checking Lodestone maintenance notices..."] = "Verificando avisos de manutenção do Lodestone...",
            ["No active or upcoming maintenance notice was found."] = "Nenhum aviso de manutenção ativo ou futuro foi encontrado.",
            ["Maintenance checked. Latest detected maintenance is already current."] = "Manutenção verificada. A manutenção detectada já está atualizada.",
            ["Maintenance checked. Latest detected maintenance is already current: {0}."] = "Manutenção verificada. A manutenção detectada já está atualizada: {0}.",
            ["Scheduled maintenance starts in {0}. ({1})"] = "A manutenção programada começa em {0}. ({1})",
            ["24 hours"] = "24 horas",
            ["1 hour"] = "1 hora",
            ["15 minutes"] = "15 minutos",
            ["Maintenance check failed: {0}"] = "Falha ao verificar manutenção: {0}",
            ["Maintenance notice found: {0}"] = "Aviso de manutenção encontrado: {0}",
            ["24 hours before"] = "24 horas antes",
            ["1 hour before"] = "1 hora antes",
            ["15 minutes before"] = "15 minutos antes",
            ["Uses {0} Lodestone maintenance notices."] = "Usa avisos de manutenção do Lodestone em {0}.",
            ["Automatic checks run only while maintenance reminders are enabled."] = "Verificações automáticas só rodam com os lembretes de manutenção ativados.",
            ["Latest Lodestone maintenance:"] = "Última manutenção do Lodestone:",
            ["No Lodestone maintenance found yet."] = "Nenhuma manutenção do Lodestone encontrada ainda.",
            ["Detected maintenance time:"] = "Horário de manutenção detectado:",
            ["Last check: {0}"] = "Última verificação: {0}",
            ["Saved Profiles"] = "Perfis salvos",
            ["Rename Active Profile"] = "Renomear perfil ativo",
            ["New Profile"] = "Novo perfil",
            ["Create From Current"] = "Criar do atual",
            ["Delete Active Profile"] = "Excluir perfil ativo",
            ["Presets"] = "Predefinições",
            ["Presets are built-in themes. Profiles are your own saved custom setups."] = "Predefinições são temas internos. Perfis são suas customizações salvas.",
            ["Layout & Style"] = "Layout e estilo",
            ["Layout Mode"] = "Modo de layout",
            ["Horizontal"] = "Horizontal",
            ["Vertical"] = "Vertical",
            ["Display Style"] = "Estilo de exibição",
            ["Classic"] = "Clássico",
            ["Minimal"] = "Minimalista",
            ["Strong Shadow"] = "Sombra forte",
            ["Soft Glass"] = "Vidro suave",
            ["Retro Panel"] = "Painel retrô",
            ["Preset"] = "Predefinição",
            ["Gold HUD"] = "HUD dourada",
            ["Apply Preset To Active Profile"] = "Aplicar predefinição ao perfil ativo",
            ["Visibility"] = "Visibilidade",
            ["Border"] = "Borda",
            ["Shadow Text"] = "Sombra do texto",
            ["Icon"] = "Ícone",
            ["Icon Border"] = "Borda do ícone",
            ["Text"] = "Texto",
            ["Text Position"] = "Posição do texto",
            ["Next Alarm Overlay Text"] = "Texto do overlay do próximo alarme",
            ["Maintenance Overlay Text"] = "Texto do overlay de manutenção",
            ["Recommend to turn off any similar feature from other plugins to avoid any issues."] = "Recomendado desativar qualquer recurso semelhante de outros plugins para evitar problemas.",
            ["Text Size"] = "Tamanho do texto",
            ["Text Color"] = "Cor do texto",
            ["Main Clock Text"] = "Texto do relógio principal",
            ["Shadow Color"] = "Cor da sombra",
            ["Background"] = "Fundo",
            ["Background Color"] = "Cor do fundo",
            ["Border Color"] = "Cor da borda",
            ["Background Opacity"] = "Opacidade do fundo",
            ["Border Opacity"] = "Opacidade da borda",
            ["Icon Text Color"] = "Cor do texto do ícone",
            ["Icon Background"] = "Fundo do ícone",
            ["Icon Border Color"] = "Cor da borda do ícone",
            ["Icon Border Opacity"] = "Opacidade da borda do ícone",
            ["Local Time Layout"] = "Layout da hora local",
            ["Placement"] = "Posição",
            ["Inside main display"] = "Dentro do painel principal",
            ["Outside main display"] = "Fora do painel principal",
            ["Inside main panel"] = "Dentro do painel principal",
            ["Outside above main panel"] = "Fora, acima do painel principal",
            ["Local Time Format"] = "Formato da hora local",
            ["Local Vertical Offset"] = "Deslocamento vertical local",
            ["Local Horizontal Offset"] = "Deslocamento horizontal local",
            ["Use this to move the local time block up/down or left/right without changing the main clock."] = "Use isso para mover o bloco da hora local sem alterar o relógio principal.",
            ["Local Time Text"] = "Texto da hora local",
            ["Local Display Style"] = "Estilo da hora local",
            ["Local Shadow Text"] = "Sombra do texto local",
            ["Local Text Color"] = "Cor do texto local",
            ["Local Text Size"] = "Tamanho do texto local",
            ["Local Time"] = "Hora local",
            ["Local Shadow Color"] = "Cor da sombra local",
            ["Local Time Icon"] = "Ícone da hora local",
            ["Local Icon"] = "Ícone local",
            ["Local Icon Text Color"] = "Cor do texto do ícone local",
            ["Local Icon Background"] = "Fundo do ícone local",
            ["Local Icon Border"] = "Borda do ícone local",
            ["Local Icon Border Color"] = "Cor da borda do ícone local",
            ["Local Icon Border Opacity"] = "Opacidade da borda do ícone local",
            ["Local Time Background"] = "Fundo da hora local",
            ["Local Background"] = "Fundo local",
            ["Local Border"] = "Borda local",
            ["Local Border Color"] = "Cor da borda local",
            ["Local Background Opacity"] = "Opacidade do fundo local",
            ["Local Border Opacity"] = "Opacidade da borda local",
            ["Local time follows its own style settings and can be placed inside or outside the main display."] = "A hora local usa suas próprias configurações de estilo e pode ficar dentro ou fora do painel principal.",
            ["Slash Commands"] = "Comandos de barra",
            ["Toggle the clock window"] = "Alterna a janela do Clock",
            ["Open settings"] = "Abre as configurações",
            ["Open settings directly on the Alarms tab"] = "Abre as configurações direto na aba Alarmes",
            ["Change the main clock timezone"] = "Altera o fuso horário principal",
            ["Change time format preset"] = "Altera o formato de hora",
            ["Change colon animation"] = "Altera a animação dos dois pontos",
            ["Change active profile layout"] = "Altera o layout do perfil ativo",
            ["Select a preset preview"] = "Seleciona uma predefinição",
            ["Lock or unlock clock movement"] = "Bloqueia ou libera o movimento do relógio",
            ["Manage profiles"] = "Gerencia perfis",
            ["Export/Import 'Clock' plugin configuration containing all configuration/customizations/Options etc"] = "Exportar/importar a configuração do plugin Clock contendo todas as configurações, customizações e opções.",
            ["Export"] = "Exportar",
            ["Import"] = "Importar",
            ["Plugin configuration exported with success!"] = "Configuração do plugin exportada com sucesso!",
            ["Plugin configuration imported with success!"] = "Configuração do plugin importada com sucesso!",
            ["Failed to export plugin configuration: {0}"] = "Falha ao exportar configuração do plugin: {0}",
            ["Failed to import plugin configuration: {0}"] = "Falha ao importar configuração do plugin: {0}"
        },
        ["fr"] = new(StringComparer.Ordinal)
        {
            ["Advanced Settings"] = "Paramètres avancés",
            ["Help"] = "Aide",
            ["Select language"] = "Choisir la langue",
            ["Search languages..."] = "Rechercher une langue...",
            ["Active Profile"] = "Profil actif",
            ["Profile"] = "Profil",
            ["No user profiles"] = "Aucun profil utilisateur",
            ["General"] = "Général",
            ["Alarms"] = "Alarmes",
            ["Profiles"] = "Profils",
            ["Appearance"] = "Apparence",
            ["Appearance Settings"] = "Paramètres d'apparence",
            ["Commands"] = "Commandes",
            ["Plugin Config"] = "Configuration du plugin",
            ["Behavior"] = "Comportement",
            ["Stick clock"] = "Verrouiller l'horloge",
            ["Auto Start"] = "Démarrage automatique",
            ["Hide during cutscenes"] = "Masquer pendant les cinématiques",
            ["Locks or unlocks movement/resizing of the clock window."] = "Verrouille ou déverrouille le déplacement/redimensionnement de l'horloge.",
            ["Automatically opens the clock after login."] = "Ouvre automatiquement l'horloge après la connexion.",
            ["Hides only the clock during cutscenes."] = "Masque uniquement l'horloge pendant les cinématiques.",
            ["Command suggestion"] = "Suggestion de commande",
            ["Show a autocompletion list when typing \"/clock\" commands"] = "Affiche une liste d’autocomplétion lors de la saisie des commandes \"/clock\"",
            ["Show next on overlay"] = "Afficher le prochain sur l’overlay",
            ["Show on main overlay"] = "Afficher sur l’overlay principal",
            ["Can't create a Alarm for the past!"] = "Impossible de créer une alarme dans le passé !",
            ["Repeat"] = "Répéter",
            ["Once"] = "Une fois",
            ["Daily"] = "Chaque jour",
            ["Weekly"] = "Chaque semaine",
            ["Weekdays"] = "Jours de semaine",
            ["Weekends"] = "Week-ends",
            ["Clock commands"] = "Commandes Clock",
            ["No Clock commands found"] = "Aucune commande Clock trouvée",
            ["Open Clock settings"] = "Ouvrir les paramètres Clock",
            ["Change the time format"] = "Changer le format de l’heure",
            ["Change the active profile layout"] = "Changer la disposition du profil actif",
            ["Compare the current time between two timezones"] = "Comparer l’heure actuelle entre deux fuseaux",
            ["Lock clock movement"] = "Verrouiller le déplacement de l’horloge",
            ["Unlock clock movement"] = "Déverrouiller le déplacement de l’horloge",
            ["Toggle the clock overlay"] = "Afficher/masquer l’overlay de l’horloge",
            ["Time Display"] = "Affichage de l'heure",
            ["Primary Timezone"] = "Fuseau horaire principal",
            ["Commonly Used"] = "Couramment utilisé",
            ["Add to favorites"] = "Ajouter aux favoris",
            ["Remove from favorites"] = "Retirer des favoris",
            ["Favorite Timezones"] = "Fuseaux favoris",
            ["Favorite timezones can be selected to change the current timezone"] = "Les fuseaux favoris peuvent être sélectionnés pour changer le fuseau actuel",
            ["No favorite timezones added yet."] = "Aucun fuseau favori ajouté.",
            ["Didn't find what you are looking for? Try by the country instead:"] = "Vous ne trouvez pas ? Essayez par pays :",
            ["Select Country"] = "Choisir un pays",
            ["Search by country and hit \"✓\" to automaticaly find timezone."] = "Recherchez par pays puis appuyez sur \"✓\" pour trouver automatiquement le fuseau.",
            ["Time Format"] = "Format de l'heure",
            ["12-hour"] = "12 heures",
            ["24-hour"] = "24 heures",
            ["12-hour + seconds"] = "12 heures + secondes",
            ["24-hour + seconds"] = "24 heures + secondes",
            ["Weekday + 24-hour"] = "Jour + 24 heures",
            ["Date + 24-hour"] = "Date + 24 heures",
            ["Show Local Time"] = "Afficher l'heure locale",
            ["Chat Timestamp"] = "Horodatage du chat",
            ["Show custom timestamp"] = "Afficher l’horodatage personnalisé",
            ["Show AM/PM"] = "Afficher AM/PM",
            ["Custom color"] = "Couleur personnalisée",
            ["Timestamp timezone"] = "Fuseau de l’horodatage",
            ["Enable \"Add timestamp to messages.\" in char config to work"] = "Activez \"Add timestamp to messages.\" dans la configuration du personnage pour fonctionner",
            ["Recommended to turn off any similar feature"] = "Il est recommandé de désactiver toute fonction similaire",
            ["from other plugins to avoid any issues."] = "des autres plugins pour éviter les problèmes.",
            ["Use typed ID: {0}"] = "Utiliser l’ID saisi : {0}",
            ["Colon Animation"] = "Animation des deux-points",
            ["Default"] = "Par défaut",
            ["Always"] = "Toujours",
            ["Hidden"] = "Masqué",
            ["Slow"] = "Lent",
            ["Fast"] = "Rapide",
            ["Create Alarm"] = "Créer une alarme",
            ["Alarm Date/Time"] = "Date/heure de l'alarme",
            ["Alarm Format"] = "Format de l'alarme",
            ["You can change it on \"General\""] = "Vous pouvez le changer dans \"Général\"",
            ["Sound"] = "Son",
            ["Alarm Message"] = "Message de l'alarme",
            ["Allow Snooze after trigger"] = "Autoriser le rappel après déclenchement",
            ["Snooze Duration"] = "Durée du rappel",
            ["minutes"] = "minutes",
            ["Add Alarm"] = "Ajouter une alarme",
            ["Test Alarm"] = "Tester l'alarme",
            ["Edit Alarm"] = "Modifier l'alarme",
            ["Alarm notifications are shown in chat and on screen."] = "Les notifications d'alarme s'affichent dans le chat et à l'écran.",
            ["Active Alarms"] = "Alarmes actives",
            ["No alarms created."] = "Aucune alarme créée.",
            ["No alarms created yet."] = "Aucune alarme créée.",
            ["Reenable Alarm for today"] = "Réactiver l'alarme pour aujourd'hui",
            ["Alarm reenabled for today"] = "Alarme réactivée pour aujourd'hui",
            ["Alarm"] = "Alarme",
            ["Alarm updated"] = "Alarme mise à jour",
            ["OK"] = "OK",
            ["Ok"] = "OK",
            ["Test"] = "Test",
            ["Snooze"] = "Rappel",
            ["Snooze will trigger at {0}"] = "Le rappel se déclenchera à {0}",
            ["Snooze already triggered."] = "Le rappel s'est déjà déclenché.",
            ["Snooze canceled."] = "Rappel annulé.",
            ["Alarm snoozed for {0} minutes"] = "Alarme reportée de {0} minutes",
            ["Maintenance Reminders"] = "Rappels de maintenance",
            ["Enable Maintenance Reminders"] = "Activer les rappels de maintenance",
            ["Lodestone Language"] = "Langue du Lodestone",
            ["Check Now"] = "Vérifier maintenant",
            ["Checking..."] = "Vérification...",
            ["Maintenance check is already running."] = "La vérification de maintenance est déjà en cours.",
            ["Checking Lodestone maintenance notices..."] = "Vérification des avis de maintenance du Lodestone...",
            ["No active or upcoming maintenance notice was found."] = "Aucun avis de maintenance actif ou à venir trouvé.",
            ["Maintenance checked. Latest detected maintenance is already current."] = "Maintenance vérifiée. La dernière maintenance détectée est déjà à jour.",
            ["Maintenance checked. Latest detected maintenance is already current: {0}."] = "Maintenance vérifiée. La dernière maintenance détectée est déjà à jour : {0}.",
            ["Scheduled maintenance starts in {0}. ({1})"] = "La maintenance programmée commence dans {0}. ({1})",
            ["24 hours"] = "24 heures",
            ["1 hour"] = "1 heure",
            ["15 minutes"] = "15 minutes",
            ["Maintenance check failed: {0}"] = "Échec de la vérification de maintenance : {0}",
            ["Maintenance notice found: {0}"] = "Avis de maintenance trouvé : {0}",
            ["24 hours before"] = "24 heures avant",
            ["1 hour before"] = "1 heure avant",
            ["15 minutes before"] = "15 minutes avant",
            ["Uses {0} Lodestone maintenance notices."] = "Utilise les avis de maintenance Lodestone en {0}.",
            ["Automatic checks run only while maintenance reminders are enabled."] = "Les vérifications automatiques ne s'exécutent que si les rappels sont activés.",
            ["Latest Lodestone maintenance:"] = "Dernière maintenance Lodestone :",
            ["No Lodestone maintenance found yet."] = "Aucune maintenance Lodestone trouvée.",
            ["Detected maintenance time:"] = "Heure de maintenance détectée :",
            ["Last check: {0}"] = "Dernière vérification : {0}",
            ["Saved Profiles"] = "Profils sauvegardés",
            ["Rename Active Profile"] = "Renommer le profil actif",
            ["New Profile"] = "Nouveau profil",
            ["Create From Current"] = "Créer depuis l'actuel",
            ["Delete Active Profile"] = "Supprimer le profil actif",
            ["Presets"] = "Préréglages",
            ["Presets are built-in themes. Profiles are your own saved custom setups."] = "Les préréglages sont des thèmes intégrés. Les profils sont vos réglages personnalisés.",
            ["Layout & Style"] = "Disposition et style",
            ["Layout Mode"] = "Mode de disposition",
            ["Horizontal"] = "Horizontal",
            ["Vertical"] = "Vertical",
            ["Display Style"] = "Style d'affichage",
            ["Classic"] = "Classique",
            ["Minimal"] = "Minimal",
            ["Strong Shadow"] = "Ombre forte",
            ["Soft Glass"] = "Verre doux",
            ["Retro Panel"] = "Panneau rétro",
            ["Preset"] = "Préréglage",
            ["Gold HUD"] = "ATH doré",
            ["Apply Preset To Active Profile"] = "Appliquer au profil actif",
            ["Visibility"] = "Visibilité",
            ["Border"] = "Bordure",
            ["Shadow Text"] = "Ombre du texte",
            ["Icon"] = "Icône",
            ["Icon Border"] = "Bordure de l'icône",
            ["Text"] = "Texte",
            ["Text Position"] = "Position du texte",
            ["Next Alarm Overlay Text"] = "Texte de l’overlay de la prochaine alarme",
            ["Maintenance Overlay Text"] = "Texte de l’overlay de maintenance",
            ["Recommend to turn off any similar feature from other plugins to avoid any issues."] = "Il est recommandé de désactiver toute fonction similaire d’autres plugins afin d’éviter les problèmes.",
            ["Text Size"] = "Taille du texte",
            ["Text Color"] = "Couleur du texte",
            ["Main Clock Text"] = "Texte de l'horloge principale",
            ["Shadow Color"] = "Couleur de l'ombre",
            ["Background"] = "Arrière-plan",
            ["Background Color"] = "Couleur d'arrière-plan",
            ["Border Color"] = "Couleur de bordure",
            ["Background Opacity"] = "Opacité de l'arrière-plan",
            ["Border Opacity"] = "Opacité de la bordure",
            ["Icon Text Color"] = "Couleur du texte de l'icône",
            ["Icon Background"] = "Arrière-plan de l'icône",
            ["Icon Border Color"] = "Couleur de bordure de l'icône",
            ["Icon Border Opacity"] = "Opacité de bordure de l'icône",
            ["Local Time Layout"] = "Disposition de l'heure locale",
            ["Placement"] = "Placement",
            ["Inside main display"] = "Dans l'affichage principal",
            ["Outside main display"] = "Hors de l'affichage principal",
            ["Inside main panel"] = "Dans le panneau principal",
            ["Outside above main panel"] = "À l'extérieur, au-dessus du panneau principal",
            ["Local Time Format"] = "Format de l'heure locale",
            ["Local Vertical Offset"] = "Décalage vertical local",
            ["Local Horizontal Offset"] = "Décalage horizontal local",
            ["Use this to move the local time block up/down or left/right without changing the main clock."] = "Utilisez ceci pour déplacer l'heure locale sans changer l'horloge principale.",
            ["Local Time Text"] = "Texte de l'heure locale",
            ["Local Display Style"] = "Style d'affichage local",
            ["Local Shadow Text"] = "Ombre du texte local",
            ["Local Text Color"] = "Couleur du texte local",
            ["Local Text Size"] = "Taille du texte local",
            ["Local Time"] = "Heure locale",
            ["Local Shadow Color"] = "Couleur de l'ombre locale",
            ["Local Time Icon"] = "Icône de l'heure locale",
            ["Local Icon"] = "Icône locale",
            ["Local Icon Text Color"] = "Couleur du texte de l'icône locale",
            ["Local Icon Background"] = "Arrière-plan de l'icône locale",
            ["Local Icon Border"] = "Bordure de l'icône locale",
            ["Local Icon Border Color"] = "Couleur de bordure de l'icône locale",
            ["Local Icon Border Opacity"] = "Opacité de bordure de l'icône locale",
            ["Local Time Background"] = "Arrière-plan de l'heure locale",
            ["Local Background"] = "Arrière-plan local",
            ["Local Border"] = "Bordure locale",
            ["Local Border Color"] = "Couleur de bordure locale",
            ["Local Background Opacity"] = "Opacité de l'arrière-plan local",
            ["Local Border Opacity"] = "Opacité de la bordure locale",
            ["Local time follows its own style settings and can be placed inside or outside the main display."] = "L'heure locale utilise ses propres réglages de style et peut être placée dans ou hors de l'affichage principal.",
            ["Slash Commands"] = "Commandes slash",
            ["Toggle the clock window"] = "Afficher/masquer la fenêtre Clock",
            ["Open settings"] = "Ouvrir les paramètres",
            ["Open settings directly on the Alarms tab"] = "Ouvrir les paramètres sur l'onglet Alarmes",
            ["Change the main clock timezone"] = "Changer le fuseau horaire principal",
            ["Change time format preset"] = "Changer le format de l'heure",
            ["Change colon animation"] = "Changer l'animation des deux-points",
            ["Change active profile layout"] = "Changer la disposition du profil actif",
            ["Select a preset preview"] = "Sélectionner un préréglage",
            ["Lock or unlock clock movement"] = "Verrouiller ou déverrouiller le déplacement",
            ["Manage profiles"] = "Gérer les profils",
            ["Export/Import 'Clock' plugin configuration containing all configuration/customizations/Options etc"] = "Exporter/importer la configuration du plugin Clock avec toutes les options et personnalisations.",
            ["Export"] = "Exporter",
            ["Import"] = "Importer",
            ["Plugin configuration exported with success!"] = "Configuration du plugin exportée avec succès !",
            ["Plugin configuration imported with success!"] = "Configuration du plugin importée avec succès !",
            ["Failed to export plugin configuration: {0}"] = "Échec de l'exportation de la configuration : {0}",
            ["Failed to import plugin configuration: {0}"] = "Échec de l'importation de la configuration : {0}"
        },
        ["de"] = new(StringComparer.Ordinal)
        {
            ["Advanced Settings"] = "Erweiterte Einstellungen",
            ["Help"] = "Hilfe",
            ["Select language"] = "Sprache auswählen",
            ["Search languages..."] = "Sprachen suchen...",
            ["Active Profile"] = "Aktives Profil",
            ["Profile"] = "Profil",
            ["No user profiles"] = "Keine Benutzerprofile",
            ["General"] = "Allgemein",
            ["Alarms"] = "Alarme",
            ["Profiles"] = "Profile",
            ["Appearance"] = "Aussehen",
            ["Appearance Settings"] = "Aussehen-Einstellungen",
            ["Commands"] = "Befehle",
            ["Plugin Config"] = "Plugin-Konfiguration",
            ["Behavior"] = "Verhalten",
            ["Stick clock"] = "Uhr fixieren",
            ["Auto Start"] = "Automatisch starten",
            ["Hide during cutscenes"] = "Während Zwischensequenzen ausblenden",
            ["Locks or unlocks movement/resizing of the clock window."] = "Sperrt oder entsperrt das Verschieben/Ändern der Größe des Uhrfensters.",
            ["Automatically opens the clock after login."] = "Öffnet die Uhr nach dem Einloggen automatisch.",
            ["Hides only the clock during cutscenes."] = "Blendet nur die Uhr während Zwischensequenzen aus.",
            ["Command suggestion"] = "Befehlvorschläge",
            ["Show a autocompletion list when typing \"/clock\" commands"] = "Zeigt beim Tippen von \"/clock\"-Befehlen eine Autovervollständigungsliste",
            ["Show next on overlay"] = "Nächsten im Overlay anzeigen",
            ["Show on main overlay"] = "Im Haupt-Overlay anzeigen",
            ["Can't create a Alarm for the past!"] = "Ein Alarm kann nicht in der Vergangenheit erstellt werden!",
            ["Repeat"] = "Wiederholen",
            ["Once"] = "Einmal",
            ["Daily"] = "Täglich",
            ["Weekly"] = "Wöchentlich",
            ["Weekdays"] = "Wochentage",
            ["Weekends"] = "Wochenenden",
            ["Clock commands"] = "Clock-Befehle",
            ["No Clock commands found"] = "Keine Clock-Befehle gefunden",
            ["Open Clock settings"] = "Clock-Einstellungen öffnen",
            ["Change the time format"] = "Zeitformat ändern",
            ["Change the active profile layout"] = "Layout des aktiven Profils ändern",
            ["Compare the current time between two timezones"] = "Aktuelle Zeit zwischen zwei Zeitzonen vergleichen",
            ["Lock clock movement"] = "Bewegung der Uhr sperren",
            ["Unlock clock movement"] = "Bewegung der Uhr entsperren",
            ["Toggle the clock overlay"] = "Uhr-Overlay umschalten",
            ["Time Display"] = "Zeitanzeige",
            ["Primary Timezone"] = "Primäre Zeitzone",
            ["Commonly Used"] = "Häufig verwendet",
            ["Add to favorites"] = "Zu Favoriten hinzufügen",
            ["Remove from favorites"] = "Aus Favoriten entfernen",
            ["Favorite Timezones"] = "Favorisierte Zeitzonen",
            ["Favorite timezones can be selected to change the current timezone"] = "Favorisierte Zeitzonen können ausgewählt werden, um die aktuelle Zeitzone zu ändern",
            ["No favorite timezones added yet."] = "Noch keine favorisierten Zeitzonen hinzugefügt.",
            ["Didn't find what you are looking for? Try by the country instead:"] = "Nicht gefunden? Versuche es stattdessen über das Land:",
            ["Select Country"] = "Land auswählen",
            ["Search by country and hit \"✓\" to automaticaly find timezone."] = "Suche nach Land und drücke \"✓\", um die Zeitzone automatisch zu finden.",
            ["Time Format"] = "Zeitformat",
            ["12-hour"] = "12 Stunden",
            ["24-hour"] = "24 Stunden",
            ["12-hour + seconds"] = "12 Stunden + Sekunden",
            ["24-hour + seconds"] = "24 Stunden + Sekunden",
            ["Weekday + 24-hour"] = "Wochentag + 24 Stunden",
            ["Date + 24-hour"] = "Datum + 24 Stunden",
            ["Show Local Time"] = "Lokale Zeit anzeigen",
            ["Chat Timestamp"] = "Chat-Zeitstempel",
            ["Show custom timestamp"] = "Benutzerdefinierten Zeitstempel anzeigen",
            ["Show AM/PM"] = "AM/PM anzeigen",
            ["Custom color"] = "Benutzerdefinierte Farbe",
            ["Timestamp timezone"] = "Zeitstempel-Zeitzone",
            ["Enable \"Add timestamp to messages.\" in char config to work"] = "Aktiviere \"Add timestamp to messages.\" in der Charakterkonfiguration, damit es funktioniert",
            ["Recommended to turn off any similar feature"] = "Es wird empfohlen, ähnliche Funktionen",
            ["from other plugins to avoid any issues."] = "anderer Plugins zu deaktivieren, um Probleme zu vermeiden.",
            ["Use typed ID: {0}"] = "Eingegebene ID verwenden: {0}",
            ["Colon Animation"] = "Doppelpunktanimation",
            ["Default"] = "Standard",
            ["Always"] = "Immer",
            ["Hidden"] = "Ausgeblendet",
            ["Slow"] = "Langsam",
            ["Fast"] = "Schnell",
            ["Create Alarm"] = "Alarm erstellen",
            ["Alarm Date/Time"] = "Alarmdatum/-zeit",
            ["Alarm Format"] = "Alarmformat",
            ["You can change it on \"General\""] = "Du kannst das unter \"Allgemein\" ändern",
            ["Sound"] = "Ton",
            ["Alarm Message"] = "Alarmnachricht",
            ["Allow Snooze after trigger"] = "Snooze nach Auslösung erlauben",
            ["Snooze Duration"] = "Snooze-Dauer",
            ["minutes"] = "Minuten",
            ["Add Alarm"] = "Alarm hinzufügen",
            ["Test Alarm"] = "Alarm testen",
            ["Edit Alarm"] = "Alarm bearbeiten",
            ["Alarm notifications are shown in chat and on screen."] = "Alarmbenachrichtigungen werden im Chat und auf dem Bildschirm angezeigt.",
            ["Active Alarms"] = "Aktive Alarme",
            ["No alarms created."] = "Keine Alarme erstellt.",
            ["No alarms created yet."] = "Keine Alarme erstellt.",
            ["Reenable Alarm for today"] = "Alarm für heute reaktivieren",
            ["Alarm reenabled for today"] = "Alarm für heute reaktiviert",
            ["Alarm"] = "Alarm",
            ["Alarm updated"] = "Alarm aktualisiert",
            ["OK"] = "OK",
            ["Ok"] = "OK",
            ["Test"] = "Test",
            ["Snooze"] = "Snooze",
            ["Snooze will trigger at {0}"] = "Snooze wird um {0} ausgelöst",
            ["Snooze already triggered."] = "Snooze wurde bereits ausgelöst.",
            ["Snooze canceled."] = "Snooze abgebrochen.",
            ["Alarm snoozed for {0} minutes"] = "Alarm um {0} Minuten verschoben",
            ["Maintenance Reminders"] = "Wartungserinnerungen",
            ["Enable Maintenance Reminders"] = "Wartungserinnerungen aktivieren",
            ["Lodestone Language"] = "Lodestone-Sprache",
            ["Check Now"] = "Jetzt prüfen",
            ["Checking..."] = "Prüfe...",
            ["Maintenance check is already running."] = "Die Wartungsprüfung läuft bereits.",
            ["Checking Lodestone maintenance notices..."] = "Prüfe Lodestone-Wartungshinweise...",
            ["No active or upcoming maintenance notice was found."] = "Keine aktive oder bevorstehende Wartung gefunden.",
            ["Maintenance checked. Latest detected maintenance is already current."] = "Wartung geprüft. Die zuletzt erkannte Wartung ist bereits aktuell.",
            ["Maintenance checked. Latest detected maintenance is already current: {0}."] = "Wartung geprüft. Die zuletzt erkannte Wartung ist bereits aktuell: {0}.",
            ["Scheduled maintenance starts in {0}. ({1})"] = "Die geplante Wartung beginnt in {0}. ({1})",
            ["24 hours"] = "24 Stunden",
            ["1 hour"] = "1 Stunde",
            ["15 minutes"] = "15 Minuten",
            ["Maintenance check failed: {0}"] = "Wartungsprüfung fehlgeschlagen: {0}",
            ["Maintenance notice found: {0}"] = "Wartungshinweis gefunden: {0}",
            ["24 hours before"] = "24 Stunden vorher",
            ["1 hour before"] = "1 Stunde vorher",
            ["15 minutes before"] = "15 Minuten vorher",
            ["Uses {0} Lodestone maintenance notices."] = "Verwendet Lodestone-Wartungshinweise in {0}.",
            ["Automatic checks run only while maintenance reminders are enabled."] = "Automatische Prüfungen laufen nur, wenn Wartungserinnerungen aktiviert sind.",
            ["Latest Lodestone maintenance:"] = "Letzte Lodestone-Wartung:",
            ["No Lodestone maintenance found yet."] = "Noch keine Lodestone-Wartung gefunden.",
            ["Detected maintenance time:"] = "Erkannte Wartungszeit:",
            ["Last check: {0}"] = "Letzte Prüfung: {0}",
            ["Saved Profiles"] = "Gespeicherte Profile",
            ["Rename Active Profile"] = "Aktives Profil umbenennen",
            ["New Profile"] = "Neues Profil",
            ["Create From Current"] = "Aus aktuellem erstellen",
            ["Delete Active Profile"] = "Aktives Profil löschen",
            ["Presets"] = "Voreinstellungen",
            ["Presets are built-in themes. Profiles are your own saved custom setups."] = "Voreinstellungen sind eingebaute Designs. Profile sind deine eigenen gespeicherten Anpassungen.",
            ["Layout & Style"] = "Layout und Stil",
            ["Layout Mode"] = "Layout-Modus",
            ["Horizontal"] = "Horizontal",
            ["Vertical"] = "Vertikal",
            ["Display Style"] = "Anzeigestil",
            ["Classic"] = "Klassisch",
            ["Minimal"] = "Minimal",
            ["Strong Shadow"] = "Starker Schatten",
            ["Soft Glass"] = "Weiches Glas",
            ["Retro Panel"] = "Retro-Panel",
            ["Preset"] = "Voreinstellung",
            ["Gold HUD"] = "Gold-HUD",
            ["Apply Preset To Active Profile"] = "Auf aktives Profil anwenden",
            ["Visibility"] = "Sichtbarkeit",
            ["Border"] = "Rand",
            ["Shadow Text"] = "Textschatten",
            ["Icon"] = "Symbol",
            ["Icon Border"] = "Symbolrand",
            ["Text"] = "Text",
            ["Text Position"] = "Textposition",
            ["Next Alarm Overlay Text"] = "Text des Overlays für den nächsten Alarm",
            ["Maintenance Overlay Text"] = "Text des Wartungs-Overlays",
            ["Recommend to turn off any similar feature from other plugins to avoid any issues."] = "Es wird empfohlen, ähnliche Funktionen anderer Plugins zu deaktivieren, um Probleme zu vermeiden.",
            ["Text Size"] = "Textgröße",
            ["Text Color"] = "Textfarbe",
            ["Main Clock Text"] = "Text der Hauptuhr",
            ["Shadow Color"] = "Schattenfarbe",
            ["Background"] = "Hintergrund",
            ["Background Color"] = "Hintergrundfarbe",
            ["Border Color"] = "Randfarbe",
            ["Background Opacity"] = "Hintergrunddeckkraft",
            ["Border Opacity"] = "Randdeckkraft",
            ["Icon Text Color"] = "Symboltextfarbe",
            ["Icon Background"] = "Symbolhintergrund",
            ["Icon Border Color"] = "Symbolrandfarbe",
            ["Icon Border Opacity"] = "Symbolranddeckkraft",
            ["Local Time Layout"] = "Layout der lokalen Zeit",
            ["Placement"] = "Platzierung",
            ["Inside main display"] = "Innerhalb der Hauptanzeige",
            ["Outside main display"] = "Außerhalb der Hauptanzeige",
            ["Inside main panel"] = "Innerhalb des Hauptpanels",
            ["Outside above main panel"] = "Außerhalb über dem Hauptpanel",
            ["Local Time Format"] = "Format der lokalen Zeit",
            ["Local Vertical Offset"] = "Vertikaler lokaler Versatz",
            ["Local Horizontal Offset"] = "Horizontaler lokaler Versatz",
            ["Use this to move the local time block up/down or left/right without changing the main clock."] = "Damit kannst du den lokalen Zeitblock verschieben, ohne die Hauptuhr zu ändern.",
            ["Local Time Text"] = "Text der lokalen Zeit",
            ["Local Display Style"] = "Lokaler Anzeigestil",
            ["Local Shadow Text"] = "Lokaler Textschatten",
            ["Local Text Color"] = "Lokale Textfarbe",
            ["Local Text Size"] = "Lokale Textgröße",
            ["Local Time"] = "Lokale Zeit",
            ["Local Shadow Color"] = "Lokale Schattenfarbe",
            ["Local Time Icon"] = "Symbol der lokalen Zeit",
            ["Local Icon"] = "Lokales Symbol",
            ["Local Icon Text Color"] = "Lokale Symboltextfarbe",
            ["Local Icon Background"] = "Lokaler Symbolhintergrund",
            ["Local Icon Border"] = "Lokaler Symbolrand",
            ["Local Icon Border Color"] = "Lokale Symbolrandfarbe",
            ["Local Icon Border Opacity"] = "Lokale Symbolranddeckkraft",
            ["Local Time Background"] = "Hintergrund der lokalen Zeit",
            ["Local Background"] = "Lokaler Hintergrund",
            ["Local Border"] = "Lokaler Rand",
            ["Local Border Color"] = "Lokale Randfarbe",
            ["Local Background Opacity"] = "Lokale Hintergrunddeckkraft",
            ["Local Border Opacity"] = "Lokale Randdeckkraft",
            ["Local time follows its own style settings and can be placed inside or outside the main display."] = "Die lokale Zeit nutzt eigene Stileinstellungen und kann innerhalb oder außerhalb der Hauptanzeige platziert werden.",
            ["Slash Commands"] = "Slash-Befehle",
            ["Toggle the clock window"] = "Clock-Fenster ein-/ausblenden",
            ["Open settings"] = "Einstellungen öffnen",
            ["Open settings directly on the Alarms tab"] = "Einstellungen direkt im Alarm-Tab öffnen",
            ["Change the main clock timezone"] = "Hauptzeitzone ändern",
            ["Change time format preset"] = "Zeitformat ändern",
            ["Change colon animation"] = "Doppelpunktanimation ändern",
            ["Change active profile layout"] = "Layout des aktiven Profils ändern",
            ["Select a preset preview"] = "Voreinstellung auswählen",
            ["Lock or unlock clock movement"] = "Bewegung der Uhr sperren oder entsperren",
            ["Manage profiles"] = "Profile verwalten",
            ["Export/Import 'Clock' plugin configuration containing all configuration/customizations/Options etc"] = "Clock-Plugin-Konfiguration mit allen Einstellungen, Anpassungen und Optionen exportieren/importieren.",
            ["Export"] = "Exportieren",
            ["Import"] = "Importieren",
            ["Plugin configuration exported with success!"] = "Plugin-Konfiguration erfolgreich exportiert!",
            ["Plugin configuration imported with success!"] = "Plugin-Konfiguration erfolgreich importiert!",
            ["Failed to export plugin configuration: {0}"] = "Export der Plugin-Konfiguration fehlgeschlagen: {0}",
            ["Failed to import plugin configuration: {0}"] = "Import der Plugin-Konfiguration fehlgeschlagen: {0}"
        },
        ["ja"] = new(StringComparer.Ordinal)
        {
            ["Advanced Settings"] = "詳細設定",
            ["Help"] = "ヘルプ",
            ["Select language"] = "言語を選択",
            ["Search languages..."] = "言語を検索...",
            ["Active Profile"] = "有効なプロファイル",
            ["Profile"] = "プロファイル",
            ["No user profiles"] = "ユーザープロファイルなし",
            ["General"] = "一般",
            ["Alarms"] = "アラーム",
            ["Profiles"] = "プロファイル",
            ["Appearance"] = "外観",
            ["Appearance Settings"] = "外観設定",
            ["Commands"] = "コマンド",
            ["Plugin Config"] = "プラグイン設定",
            ["Behavior"] = "動作",
            ["Stick clock"] = "時計を固定",
            ["Auto Start"] = "自動起動",
            ["Hide during cutscenes"] = "カットシーン中は非表示",
            ["Locks or unlocks movement/resizing of the clock window."] = "時計ウィンドウの移動とサイズ変更をロックまたは解除します。",
            ["Automatically opens the clock after login."] = "ログイン後に時計を自動で開きます。",
            ["Hides only the clock during cutscenes."] = "カットシーン中は時計だけを非表示にします。",
            ["Command suggestion"] = "コマンド候補",
            ["Show a autocompletion list when typing \"/clock\" commands"] = "「/clock」コマンド入力中に補完リストを表示します",
            ["Show next on overlay"] = "次をオーバーレイに表示",
            ["Show on main overlay"] = "メインオーバーレイに表示",
            ["Can't create a Alarm for the past!"] = "過去の時刻にはアラームを作成できません！",
            ["Repeat"] = "繰り返し",
            ["Once"] = "1回",
            ["Daily"] = "毎日",
            ["Weekly"] = "毎週",
            ["Weekdays"] = "平日",
            ["Weekends"] = "週末",
            ["Clock commands"] = "Clock コマンド",
            ["No Clock commands found"] = "Clock コマンドが見つかりません",
            ["Open Clock settings"] = "Clock 設定を開く",
            ["Change the time format"] = "時刻形式を変更",
            ["Change the active profile layout"] = "アクティブプロファイルのレイアウトを変更",
            ["Compare the current time between two timezones"] = "2つのタイムゾーンの現在時刻を比較",
            ["Lock clock movement"] = "時計の移動をロック",
            ["Unlock clock movement"] = "時計の移動ロックを解除",
            ["Toggle the clock overlay"] = "時計オーバーレイを切り替え",
            ["Time Display"] = "時刻表示",
            ["Primary Timezone"] = "メインタイムゾーン",
            ["Commonly Used"] = "よく使われる",
            ["Add to favorites"] = "お気に入りに追加",
            ["Remove from favorites"] = "お気に入りから削除",
            ["Favorite Timezones"] = "お気に入りのタイムゾーン",
            ["Favorite timezones can be selected to change the current timezone"] = "お気に入りのタイムゾーンを選択すると現在のタイムゾーンを変更できます",
            ["No favorite timezones added yet."] = "お気に入りのタイムゾーンはまだありません。",
            ["Didn't find what you are looking for? Try by the country instead:"] = "見つからない場合は国名で検索してください:",
            ["Select Country"] = "国を選択",
            ["Search by country and hit \"✓\" to automaticaly find timezone."] = "国名で検索し、\"✓\" を押すとタイムゾーンを自動検索します。",
            ["Time Format"] = "時刻形式",
            ["12-hour"] = "12時間",
            ["24-hour"] = "24時間",
            ["12-hour + seconds"] = "12時間 + 秒",
            ["24-hour + seconds"] = "24時間 + 秒",
            ["Weekday + 24-hour"] = "曜日 + 24時間",
            ["Date + 24-hour"] = "日付 + 24時間",
            ["Show Local Time"] = "ローカル時刻を表示",
            ["Chat Timestamp"] = "チャットのタイムスタンプ",
            ["Show custom timestamp"] = "カスタムタイムスタンプを表示",
            ["Show AM/PM"] = "AM/PMを表示",
            ["Custom color"] = "カスタム色",
            ["Timestamp timezone"] = "タイムスタンプのタイムゾーン",
            ["Enable \"Add timestamp to messages.\" in char config to work"] = "機能させるにはキャラクター設定の「Add timestamp to messages.」を有効にしてください",
            ["Recommended to turn off any similar feature"] = "問題を避けるため、他のプラグインの",
            ["from other plugins to avoid any issues."] = "同様の機能は無効にすることをおすすめします。",
            ["Use typed ID: {0}"] = "入力したIDを使用: {0}",
            ["Colon Animation"] = "コロンのアニメーション",
            ["Default"] = "標準",
            ["Always"] = "常に表示",
            ["Hidden"] = "非表示",
            ["Slow"] = "遅い",
            ["Fast"] = "速い",
            ["Create Alarm"] = "アラーム作成",
            ["Alarm Date/Time"] = "アラーム日時",
            ["Alarm Format"] = "アラーム形式",
            ["You can change it on \"General\""] = "\"一般\"で変更できます",
            ["Sound"] = "サウンド",
            ["Alarm Message"] = "アラームメッセージ",
            ["Allow Snooze after trigger"] = "発動後のスヌーズを許可",
            ["Snooze Duration"] = "スヌーズ時間",
            ["minutes"] = "分",
            ["Add Alarm"] = "アラームを追加",
            ["Test Alarm"] = "アラームをテスト",
            ["Edit Alarm"] = "アラームを編集",
            ["Alarm notifications are shown in chat and on screen."] = "アラーム通知はチャットと画面に表示されます。",
            ["Active Alarms"] = "有効なアラーム",
            ["No alarms created."] = "アラームは作成されていません。",
            ["No alarms created yet."] = "アラームは作成されていません。",
            ["Reenable Alarm for today"] = "今日のアラームを再有効化",
            ["Alarm reenabled for today"] = "今日のアラームを再有効化しました",
            ["Alarm"] = "アラーム",
            ["Alarm updated"] = "アラームを更新しました",
            ["OK"] = "OK",
            ["Ok"] = "OK",
            ["Test"] = "テスト",
            ["Snooze"] = "スヌーズ",
            ["Snooze will trigger at {0}"] = "スヌーズは {0} に発動します",
            ["Snooze already triggered."] = "スヌーズはすでに発動しました。",
            ["Snooze canceled."] = "スヌーズをキャンセルしました。",
            ["Alarm snoozed for {0} minutes"] = "アラームを{0}分スヌーズしました",
            ["Maintenance Reminders"] = "メンテナンス通知",
            ["Enable Maintenance Reminders"] = "メンテナンス通知を有効化",
            ["Lodestone Language"] = "Lodestone言語",
            ["Check Now"] = "今すぐ確認",
            ["Checking..."] = "確認中...",
            ["Maintenance check is already running."] = "メンテナンス確認はすでに実行中です。",
            ["Checking Lodestone maintenance notices..."] = "Lodestoneのメンテナンス告知を確認中...",
            ["No active or upcoming maintenance notice was found."] = "現在または今後のメンテナンス告知は見つかりませんでした。",
            ["Maintenance checked. Latest detected maintenance is already current."] = "確認完了。検出済みの最新メンテナンスはすでに最新です。",
            ["Maintenance checked. Latest detected maintenance is already current: {0}."] = "確認完了。検出済みの最新メンテナンスはすでに最新です: {0}。",
            ["Scheduled maintenance starts in {0}. ({1})"] = "予定メンテナンスは{0}後に開始します。({1})",
            ["24 hours"] = "24時間",
            ["1 hour"] = "1時間",
            ["15 minutes"] = "15分",
            ["Maintenance check failed: {0}"] = "メンテナンス確認に失敗しました: {0}",
            ["Maintenance notice found: {0}"] = "メンテナンス告知を検出: {0}",
            ["24 hours before"] = "24時間前",
            ["1 hour before"] = "1時間前",
            ["15 minutes before"] = "15分前",
            ["Uses {0} Lodestone maintenance notices."] = "{0} のLodestoneメンテナンス告知を使用します。",
            ["Automatic checks run only while maintenance reminders are enabled."] = "自動確認はメンテナンス通知が有効な場合のみ実行されます。",
            ["Latest Lodestone maintenance:"] = "最新のLodestoneメンテナンス:",
            ["No Lodestone maintenance found yet."] = "Lodestoneメンテナンスはまだ見つかっていません。",
            ["Detected maintenance time:"] = "検出されたメンテナンス時刻:",
            ["Last check: {0}"] = "最終確認: {0}",
            ["Saved Profiles"] = "保存済みプロファイル",
            ["Rename Active Profile"] = "有効なプロファイル名を変更",
            ["New Profile"] = "新規プロファイル",
            ["Create From Current"] = "現在の設定から作成",
            ["Delete Active Profile"] = "有効なプロファイルを削除",
            ["Presets"] = "プリセット",
            ["Presets are built-in themes. Profiles are your own saved custom setups."] = "プリセットは内蔵テーマです。プロファイルは保存したカスタム設定です。",
            ["Layout & Style"] = "レイアウトとスタイル",
            ["Layout Mode"] = "レイアウトモード",
            ["Horizontal"] = "横",
            ["Vertical"] = "縦",
            ["Display Style"] = "表示スタイル",
            ["Classic"] = "クラシック",
            ["Minimal"] = "ミニマル",
            ["Strong Shadow"] = "強い影",
            ["Soft Glass"] = "ソフトグラス",
            ["Retro Panel"] = "レトロパネル",
            ["Preset"] = "プリセット",
            ["Gold HUD"] = "ゴールドHUD",
            ["Apply Preset To Active Profile"] = "有効なプロファイルに適用",
            ["Visibility"] = "表示",
            ["Border"] = "枠線",
            ["Shadow Text"] = "文字の影",
            ["Icon"] = "アイコン",
            ["Icon Border"] = "アイコン枠線",
            ["Text"] = "テキスト",
            ["Text Position"] = "文字位置",
            ["Next Alarm Overlay Text"] = "次のアラームのオーバーレイ文字",
            ["Maintenance Overlay Text"] = "メンテナンスのオーバーレイ文字",
            ["Recommend to turn off any similar feature from other plugins to avoid any issues."] = "問題を避けるため、他のプラグインの同様の機能は無効にすることをおすすめします。",
            ["Text Size"] = "文字サイズ",
            ["Text Color"] = "文字色",
            ["Main Clock Text"] = "メイン時計の文字",
            ["Shadow Color"] = "影の色",
            ["Background"] = "背景",
            ["Background Color"] = "背景色",
            ["Border Color"] = "枠線の色",
            ["Background Opacity"] = "背景の不透明度",
            ["Border Opacity"] = "枠線の不透明度",
            ["Icon Text Color"] = "アイコン文字色",
            ["Icon Background"] = "アイコン背景",
            ["Icon Border Color"] = "アイコン枠線色",
            ["Icon Border Opacity"] = "アイコン枠線の不透明度",
            ["Local Time Layout"] = "ローカル時刻のレイアウト",
            ["Placement"] = "配置",
            ["Inside main display"] = "メイン表示内",
            ["Outside main display"] = "メイン表示外",
            ["Inside main panel"] = "メインパネル内",
            ["Outside above main panel"] = "メインパネルの上",
            ["Local Time Format"] = "ローカル時刻形式",
            ["Local Vertical Offset"] = "ローカル縦位置",
            ["Local Horizontal Offset"] = "ローカル横位置",
            ["Use this to move the local time block up/down or left/right without changing the main clock."] = "メイン時計を変えずにローカル時刻ブロックを上下左右に移動します。",
            ["Local Time Text"] = "ローカル時刻の文字",
            ["Local Display Style"] = "ローカル表示スタイル",
            ["Local Shadow Text"] = "ローカル文字の影",
            ["Local Text Color"] = "ローカル文字色",
            ["Local Text Size"] = "ローカル文字サイズ",
            ["Local Time"] = "ローカル時刻",
            ["Local Shadow Color"] = "ローカル影色",
            ["Local Time Icon"] = "ローカル時刻アイコン",
            ["Local Icon"] = "ローカルアイコン",
            ["Local Icon Text Color"] = "ローカルアイコン文字色",
            ["Local Icon Background"] = "ローカルアイコン背景",
            ["Local Icon Border"] = "ローカルアイコン枠線",
            ["Local Icon Border Color"] = "ローカルアイコン枠線色",
            ["Local Icon Border Opacity"] = "ローカルアイコン枠線の不透明度",
            ["Local Time Background"] = "ローカル時刻の背景",
            ["Local Background"] = "ローカル背景",
            ["Local Border"] = "ローカル枠線",
            ["Local Border Color"] = "ローカル枠線色",
            ["Local Background Opacity"] = "ローカル背景の不透明度",
            ["Local Border Opacity"] = "ローカル枠線の不透明度",
            ["Local time follows its own style settings and can be placed inside or outside the main display."] = "ローカル時刻は独自のスタイル設定を使用し、メイン表示の内外に配置できます。",
            ["Slash Commands"] = "スラッシュコマンド",
            ["Toggle the clock window"] = "Clockウィンドウの表示を切り替え",
            ["Open settings"] = "設定を開く",
            ["Open settings directly on the Alarms tab"] = "アラームタブで設定を開く",
            ["Change the main clock timezone"] = "メイン時計のタイムゾーンを変更",
            ["Change time format preset"] = "時刻形式を変更",
            ["Change colon animation"] = "コロンのアニメーションを変更",
            ["Change active profile layout"] = "有効なプロファイルのレイアウトを変更",
            ["Select a preset preview"] = "プリセットを選択",
            ["Lock or unlock clock movement"] = "時計の移動をロック/解除",
            ["Manage profiles"] = "プロファイルを管理",
            ["Export/Import 'Clock' plugin configuration containing all configuration/customizations/Options etc"] = "Clockプラグインのすべての設定、カスタマイズ、オプションをエクスポート/インポートします。",
            ["Export"] = "エクスポート",
            ["Import"] = "インポート",
            ["Plugin configuration exported with success!"] = "プラグイン設定をエクスポートしました!",
            ["Plugin configuration imported with success!"] = "プラグイン設定をインポートしました!",
            ["Failed to export plugin configuration: {0}"] = "プラグイン設定のエクスポートに失敗しました: {0}",
            ["Failed to import plugin configuration: {0}"] = "プラグイン設定のインポートに失敗しました: {0}"
        }
    };

    public static ClockLanguageOption[] GetLanguageOptions()
    {
        return LanguageOptions;
    }

    public static string Translate(string cultureName, string text)
    {
        if (string.IsNullOrWhiteSpace(text))
            return text;

        var cultureKey = GetCultureKey(cultureName);
        if (!Translations.TryGetValue(cultureKey, out var table))
            return text;

        if (table.TryGetValue(text, out var translated))
            return translated;

        const string currentPrefix = "Maintenance checked. Latest detected maintenance is already current: ";
        if (text.StartsWith(currentPrefix, StringComparison.Ordinal) && text.EndsWith(".", StringComparison.Ordinal) &&
            table.TryGetValue("Maintenance checked. Latest detected maintenance is already current: {0}.", out var currentTemplate))
            return string.Format(currentTemplate, text[currentPrefix.Length..^1]);

        const string failurePrefix = "Maintenance check failed: ";
        if (text.StartsWith(failurePrefix, StringComparison.Ordinal) && table.TryGetValue("Maintenance check failed: {0}", out var failureTemplate))
            return string.Format(failureTemplate, text[failurePrefix.Length..]);

        const string foundPrefix = "Maintenance notice found: ";
        if (text.StartsWith(foundPrefix, StringComparison.Ordinal) && table.TryGetValue("Maintenance notice found: {0}", out var foundTemplate))
            return string.Format(foundTemplate, text[foundPrefix.Length..]);

        return text;
    }

    public static string GetCultureDisplayName(string cultureName)
    {
        var option = LanguageOptions.FirstOrDefault(language => string.Equals(language.CultureName, cultureName, StringComparison.OrdinalIgnoreCase));
        return option?.DisplayName ?? "English (US)";
    }

    public static CultureInfo GetCultureInfo(string cultureName)
    {
        try
        {
            return CultureInfo.GetCultureInfo(string.IsNullOrWhiteSpace(cultureName) ? "en-US" : cultureName);
        }
        catch
        {
            return CultureInfo.GetCultureInfo("en-US");
        }
    }

    public static bool MatchesFilter(ClockLanguageOption option, string filter)
    {
        if (string.IsNullOrWhiteSpace(filter))
            return true;

        var needle = filter.Trim();
        return option.DisplayName.Contains(needle, StringComparison.OrdinalIgnoreCase)
            || option.CultureName.Contains(needle, StringComparison.OrdinalIgnoreCase);
    }

    private static string GetCultureKey(string cultureName)
    {
        if (string.IsNullOrWhiteSpace(cultureName))
            return "en";

        try
        {
            var culture = CultureInfo.GetCultureInfo(cultureName);
            return culture.TwoLetterISOLanguageName;
        }
        catch
        {
            return "en";
        }
    }
}
